#!/bin/bash

GREP_RES=/tmp/lifigrep_res
MAX_LINE_COUNT_WIHTOUT_LESS=20

wth_not_name=""
inverse_grep=""
pathes=()
files=()
regexps=()

while getopts "nvp:f:r:" options
do
    case ${options} in
        n)
            with_not_name="-not "
            ;;
        p)
            pathes+="$OPTARG "
            ;;
        f)
            files+="$OPTARG "
            ;;
        v)
            inverse_grep="-v "
            ;;
        r)
            regexps+="$OPTARG "
            ;;

    esac
done

#from http://stackoverflow.com/questions/11742996/shell-script-is-mixing-getopts-with-positional-parameters-possible
#path=${@:$OPTIND:1}
#file=${@:$OPTIND+1:1}
#pattern=${@:$OPTIND+2:1}

test=${@:$OPTIND:1}

find_names=""
grep_patterns=""

for i in ${files[@]}
do
    find_names+="${with_not_name}-name $i "
done

for i in ${regexps[@]}
do
    grep_patterns+="($i)|"
done

grep_patterns=`echo $grep_patterns|sed 's/.$//'`

find ${pathes[@]} -not -name "*.tags" $find_names -exec grep --color=always -I -s -n -i $inverse_grep -E "$grep_patterns"  {} + > $GREP_RES

declare -i lc=$(wc -l $GREP_RES | awk '{print $1}')

if [ $lc -gt $MAX_LINE_COUNT_WIHTOUT_LESS ]; then
    cat $GREP_RES | less -r
else
    cat $GREP_RES
fi

/bin/rm $GREP_RES

