#!/bin/bash

LogFile=vsbuild_tmp
LogPath=/tmp/$LogFile

function usage() {
    sep="awk 'BEGIN {FS=\":\"} {printf \"%s \t %s\\n\", \$1, \$2}'"

    echo ""
    echo "Usage: li3dsbuild [atv] sln_file"
    echo ""
    echo "Build a visual studio sln using devenv under Cygwin terminal"
    echo ""
    echo "-a action.:action is one of \"b|build\", \"r|rebuild\" or \"c|clean\""|eval $sep
    echo "-t type.  :type is one of \"d64|d\", \"r64|r\""|eval $sep
    echo "-w.       :include warning info."|eval $sep
    echo "-v.       :verbose. show the underlying commands executed."|eval $sep
}

echo "" > $LogPath
touch $LogPath

action_arg=""
type_arg=""
verbose_arg="false"
with_warning="false"

while getopts "a:t:vw" options
do
    case ${options} in
        a)
            action_arg=$OPTARG   
            ;;
        t)
            type_arg=$OPTARG   
            ;;
        v)
            verbose_arg="true"
            ;;
        w)
            with_warning="true"
            ;;
    esac
done

Action=""
if [ "$action_arg" == "build" ] || [ "$action_arg" == "b" ] || [ "$action_arg" == "" ]; then
    Action="/Build"
elif [ "$action_arg" == "rebuild" ] || [ "$action_arg" == "rebuild" ]; then
    Action="/Rebuild"
elif [ "$action_arg" == "clean" ] || [ "$action_arg" == "c" ]; then 
    Action="/Clean"
else
    echo "$action_arg: error arg"
    exit -1
fi

Type=""
if [ "$type_arg" == "d64" ] || [ "$type_arg" == "d" ] || [ "$type_arg" == "" ]; then
    Type="Debug|x64"
elif [ "$type_arg" == "r64" ] || [ "$type_arg" == "r" ]; then
    Type="Release|x64"
else
    echo "$type_arg: error arg"
    exit -1
fi

#from http://stackoverflow.com/questions/11742996/shell-script-is-mixing-getopts-with-positional-parameters-possible
Target=${@:$OPTIND:1}

if [ "$Target" ==  "" ]; then
    echo "error: expects a .sln target."
    usage
    exit -1
elif [ ! -f "$Target" ]; then
    echo "$Target: target doesn't exist."
    usage
    exit -1
fi

#echo "$Target $Action $Type"
Command="devenv \"`eval cygpath -w \\\"$Target\\\"`\" \"$Action\" \"$Type\" /Out \"`eval cygpath -w \\\"$LogPath\\\"`\""
eval $Command

grep_pattern="\([0-9]+\).*error.*$"

echo $with_warning
if [ "$with_warning" == "true" ]; then
    grep_pattern=${grep_pattern}"|\([0-9]+\).*warning.*$"
fi

Catres="cat $LogPath | /bin/grep --color -E \"$grep_pattern\""
eval $Catres

if [ "$verbose_arg" == "true" ]; then
    echo "verbose mode: the executed commands is"
    echo "    $Command"
    echo "    $Catres"

fi

echo "build log is at path: $LogPath"

exit 0
